exclude: 'tests/'
repos:
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.9
  -   repo: https://github.com/pycqa/flake8
      rev: '4.0.1'  # pick a git hash / tag to point to
      hooks:
      -   id: flake8
          args: ['--ignore=E501']

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v0.931'  # Use the sha / tag you want to point at
      hooks:
      -   id: mypy
          args: ['--exclude=src/container/migrations/*', '--ignore-missing-imports']