version: '3.7'
services:
    postgres:
        image: postgres:14-alpine3.15
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
        ports:
          - '5432:5432'